BUILDDIR=build

SLIDES=$(BUILDDIR)/slides.html
REVEALJS=node_modules/reveal.js
METADATA=metadata.yaml

.PHONY: all
all: slides

.PHONY:slides
slides: $(SLIDES)

.PHONY:watch
watch:
	@echo 'Building...' && \
	make all && \
	fswatch \
		--exclude=$(BUILDDIR) \
		--one-per-batch \
		. \
	| \
	xargs -I {} sh -c 'echo Change detected. Building... && make && echo Build finished'

$(BUILDDIR)/slides.html: slides.md $(METADATA) $(REVEALJS) $(BUILDDIR)
	pandoc $< \
		--standalone \
		--from markdown+smart \
		--to revealjs \
		--filter pandoc-crossref \
		--citeproc \
		--metadata-file=$(METADATA) \
		--self-contained \
		--variable revealjs-url=./$(REVEALJS) \
		--variable theme="<%- theme %>" \
		--variable transition="<%- transition %>" \
		--variable slideNumber="<%- showSlideNumbers %>" \
		--variable showSlideNumber="<%- showSlideNumbers %>" \
		--output $@

$(REVEALJS):
	npm install

$(BUILDDIR):
	mkdir -p $(BUILDDIR)

.PHONY: clean
clean:
	@rm -rf $(BUILDDIR)
