BUILDDIR=build

SLIDES=$(BUILDDIR)/slides.html
REVEALJS=node_modules/reveal.js
METADATA=metadata.yaml

.PHONY:slides
slides: $(SLIDES)

.PHONY: all
all: slides

$(BUILDDIR)/slides.html: slides.md $(METADATA) $(REVEALJS) $(BUILDDIR)
	pandoc $< \
		--standalone \
		--from markdown+smart \
		--to revealjs \
		--filter pandoc-include-code \
		--metadata-file=$(METADATA) \
		-M date="`date "+%B%e, %Y"`" \
		--self-contained \
		--variable revealjs-url=./$(REVEALJS) \
		--variable theme="<%- theme %>" \
		--variable transition="<%- transition %>" \
		--variable slideNumber="<%- showSlideNumbers %>" \
		--variable showSlideNumber="<%- showSlideNumbers %>" \
		--output $@

$(REVEALJS):
	npm install

$(BUILDDIR):
	mkdir -p $(BUILDDIR)
